name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core_version_requirement: ^8.7.7 || ^9
dependencies:
  - examples:examples
